title: Ravishankar Sivasubramaniam
author: Ravishankar Sivasubramaniam
email: ravi_siva@live.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Ravishankar Sivasubramaniam developer mentor leader charlotte north carlina.

# social links
twitter_username: ravishankar_s # DO NOT include the @ character, or else the build will fail!
github_username:  ravishan16 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
